server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/dev/study/native-file-repo
        git:
          #          uri: file:///Users/developia/dev/study/git-local-repo
          uri: https://github.com/developiaa/{git repository name} # 깃허브 운용시
        # private repository
#          username: [username]
#          password: [password]

